"""
Alembic script.py.mako template — do not edit manually.
"""
"""initial schema

Revision ID: 7212fd6c4ca5
Revises: 
Create Date: 2026-03-25 12:05:29.117044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7212fd6c4ca5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_first_name', sa.String(), nullable=True),
    sa.Column('contact_function', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_index(op.f('ix_contacts_contact_email'), 'contacts', ['contact_email'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PENDING', 'OWNER', 'COMMERCIAL', 'VALIDATOR', 'COSTING_TEAM', 'PLANT_MANAGER', name='userrole'), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('validation_matrix',
    sa.Column('product_line', sa.String(), nullable=False),
    sa.Column('acronym', sa.String(), nullable=False),
    sa.Column('n3_kam_limit', sa.Integer(), nullable=False),
    sa.Column('n2_zone_limit', sa.Integer(), nullable=False),
    sa.Column('n1_vp_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_line'),
    sa.UniqueConstraint('acronym', name='uq_validation_matrix_acronym')
    )
    op.create_table('rfq',
    sa.Column('rfq_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT_GRP_1', 'DRAFT_GRP_2', 'DRAFT_GRP_3', 'PENDING_VALIDATION', 'IN_COSTING', 'OFFER_PREPARATION', 'OFFER_VALIDATION', 'REJECTED', 'PO_SECURED', name='rfqstatus'), nullable=False),
    sa.Column('product_line_acronym', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('validator_email', sa.String(), nullable=True),
    sa.Column('created_by_email', sa.String(), nullable=False),
    sa.Column('rfq_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chat_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('autopsy_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_email'], ['users.email'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_line_acronym'], ['validation_matrix.acronym'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('rfq_id')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('rfq_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfq.rfq_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_rfq_id'), 'audit_logs', ['rfq_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_rfq_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('rfq')
    op.drop_table('validation_matrix')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_contacts_contact_email'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
