from sqlalchemy import BigInteger, CheckConstraint, Column, Integer, Text

from app.database import Base


class OldRfqRaw(Base):
    __tablename__ = "old_rfqs"

    __table_args__ = (
        CheckConstraint(
            "row_type IN ('project', 'subitem', 'empty')",
            name="old_rfqs_raw_row_type_check",
        ),
        {"schema": "public"},
    )

    import_id = Column(BigInteger, primary_key=True, autoincrement=True)
    excel_row_number = Column(Integer, nullable=False)
    row_type = Column(Text, nullable=False)

    name = Column(Text)
    sous_elements = Column(Text)
    subitems_est_price = Column(Text)
    product_type = Column(Text)
    sous_elements_sales_limit_3 = Column(Text)
    twc_k = Column(Text)
    miror_gmdc_k = Column(Text)
    authorization_required = Column(Text)
    capex_k = Column(Text)
    capital_k = Column(Text)
    gmdc_project_k = Column(Text)
    sales_project = Column(Text)
    requester = Column(Text)
    kam = Column(Text)
    project_sales_k = Column(Text)
    gmdc_proj = Column(Text)
    customers = Column(Text)
    old_new = Column(Text)
    dup_of_old_new = Column(Text)
    cust_text = Column(Text)
    fichier = Column(Text)
    challenges = Column(Text)
    type_business = Column(Text)
    importance = Column(Text)
    application = Column(Text)
    sector = Column(Text)
    pre_sales_project_manager = Column(Text)
    gmdc_proj_2 = Column(Text)
    cust_application = Column(Text)
    assembly_location = Column(Text)
    sop = Column(Text)
    success_rate = Column(Text)
    volume_profile = Column(Text)
    bouton = Column(Text)
    avg_difficulty = Column(Text)
    avg_dev_axis = Column(Text)
    avg_gmdc_ce = Column(Text)
    new_customer_index = Column(Text)
    interest_index = Column(Text)
    sop_speed_index = Column(Text)
    confidance_index = Column(Text)
    gmdc_index = Column(Text)
    gmdc_value_index = Column(Text)
    global_rating = Column(Text)
    year_to_sop = Column(Text)
    lifetime_index = Column(Text)
    life_time_year = Column(Text)
    number_of_components = Column(Text)
    project_name = Column(Text)
    id_2 = Column(Text)
    costing_n = Column(Text)
    plant_to_deliver = Column(Text)
    cust_project_name = Column(Text)
    identifiant_de_l_element = Column(Text)
    chiffres_id = Column(Text)
    text_vol_profile = Column(Text)
    sop_2 = Column(Text)
    sop_1 = Column(Text)
    sop_2_2 = Column(Text)
    sop_3 = Column(Text)
    sop_4 = Column(Text)
    sop_5 = Column(Text)
    sop_6 = Column(Text)
    sop_7 = Column(Text)
    sop_8 = Column(Text)
    sop_9 = Column(Text)
    readiness = Column(Text)
    project_condition = Column(Text)
    product_testing = Column(Text)
    plant_audited = Column(Text)
    iteration = Column(Text)
    integration = Column(Text)
    final_delivery = Column(Text)
    creation_log = Column(Text)
    duplicate_of_pipe_line = Column(Text)
    duplicate_of_pipeline_record_change = Column(Text)
    id_test = Column(Text)
    link_to_duplicate_of_pipe_line = Column(Text)
    status_name = Column(Text)
    monday_doc = Column(Text)
    avg_difficulty_2 = Column(Text)
    development_axis = Column(Text)
    dup_of_development_axis = Column(Text)
    menu_deroulant = Column(Text)
    total_qty = Column(Text)
    note = Column(Text)
    journal_de_creation = Column(Text)
    miroir = Column(Text)
