from sqlalchemy import BigInteger, Column, ForeignKey, Integer, Text
from sqlalchemy.orm import relationship

from app.database import Base


class OldRfqMonday(Base):
    __tablename__ = "old_rfqs_monday"
    __table_args__ = {"schema": "public"}

    old_rfq_id = Column(BigInteger, primary_key=True, index=True)
    excel_row_number = Column(Integer)
    name = Column(Text)
    subitems_est_price_eur = Column(Text)
    product_type = Column(Text)
    subelements_sales_limit_3 = Column(Text)
    twc_keur = Column(Text)
    mirror_gmdc_k = Column(Text)
    authorization_required = Column(Text)
    capex_keur = Column(Text)
    capital_keur = Column(Text)
    gmdc_project_keur = Column(Text)
    sales_project = Column(Text)
    requester = Column(Text)
    kam = Column(Text)
    project_sales_keur = Column(Text)
    gmdc_proj_percent = Column(Text)
    customers = Column(Text)
    old_new = Column(Text)
    duplicate_of_old_new = Column(Text)
    customer_text = Column(Text)
    type_business = Column(Text)
    importance = Column(Text)
    application = Column(Text)
    sector = Column(Text)
    pre_sales_project_manager = Column(Text)
    gmdc_proj = Column(Text)
    customer_application = Column(Text)
    sop = Column(Text)
    success_rate = Column(Text)
    volume_profile = Column(Text)
    button = Column(Text)
    interest_index = Column(Text)
    sop_speed_index = Column(Text)
    confidence_index = Column(Text)
    gmdc_percent_index = Column(Text)
    gmdc_value_index = Column(Text)
    year_to_sop = Column(Text)
    lifetime_index = Column(Text)
    lifetime_year = Column(Text)
    project_name = Column(Text)
    monday_id = Column(Text)
    costing_number = Column(Text)
    plant_to_deliver = Column(Text)
    customer_project_name = Column(Text)
    element_identifier = Column(Text)
    chiffres_id = Column(Text)
    text_volume_profile = Column(Text)
    sop_percent = Column(Text)
    sop_percent_1 = Column(Text)
    sop_percent_2 = Column(Text)
    sop_percent_3 = Column(Text)
    sop_percent_4 = Column(Text)
    sop_percent_5 = Column(Text)
    sop_percent_6 = Column(Text)
    sop_percent_7 = Column(Text)
    sop_percent_8 = Column(Text)
    sop_percent_9 = Column(Text)
    readiness = Column(Text)
    project_condition = Column(Text)
    product_testing = Column(Text)
    plant_audited = Column(Text)
    iteration = Column(Text)
    integration = Column(Text)
    final_delivery = Column(Text)
    creation_log = Column(Text)
    duplicate_of_pipeline = Column(Text)
    duplicate_of_pipeline_record_change = Column(Text)
    id_test = Column(Text)
    status_name = Column(Text)
    duplicate_of_development_axis = Column(Text)
    total_qty = Column(Text)
    note = Column(Text)
    creation_journal = Column(Text)
    mirror = Column(Text)

    subitems = relationship(
        "OldRfqSubitem",
        back_populates="rfq",
        cascade="all, delete-orphan",
        order_by="OldRfqSubitem.subitem_order.asc()",
    )


class OldRfqSubitem(Base):
    __tablename__ = "old_rfq_subitems"
    __table_args__ = {"schema": "public"}

    old_rfq_subitem_id = Column(BigInteger, primary_key=True, index=True)
    old_rfq_id = Column(
        BigInteger,
        ForeignKey("public.old_rfqs_monday.old_rfq_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    excel_row_number = Column(Integer)
    subitem_order = Column(Integer)
    name = Column(Text)
    product_types = Column(Text)
    qty_kp = Column(Text)
    est_price_eur = Column(Text)
    std_gmdc_percent = Column(Text)
    std_gmdc_percent_2 = Column(Text)
    product_line_labels = Column(Text)
    product_line_labels_text = Column(Text)
    difficulty = Column(Text)
    capacity_steps_mp = Column(Text)
    capacity_steps_mp_2 = Column(Text)
    capex_per_mp = Column(Text)
    capex_per_mp_2 = Column(Text)
    development_axis = Column(Text)
    twc_percent = Column(Text)
    twc_percent_2 = Column(Text)
    parent_id = Column(Text)
    delivery_to = Column(Text)
    final_delivery = Column(Text)
    plant = Column(Text)
    application = Column(Text)
    type_sales = Column(Text)
    success_rate = Column(Text)
    sales_ke = Column(Text)
    gmdc_keur = Column(Text)
    roce_ro_cap = Column(Text)
    roce_gmdc_cap = Column(Text)
    twc = Column(Text)
    capex_keur = Column(Text)
    capital = Column(Text)
    status = Column(Text)
    importance = Column(Text)
    project_name = Column(Text)
    customer = Column(Text)
    pipeline = Column(Text)
    iteration = Column(Text)
    safe_sales_keur = Column(Text)
    product_line_description = Column(Text)
    authorization_required = Column(Text)
    product_types_2 = Column(Text)
    subitem_id = Column(Text)
    chiffre_subitem_id = Column(Text)
    sales_limit_1 = Column(Text)
    sales_limit_3 = Column(Text)

    rfq = relationship("OldRfqMonday", back_populates="subitems")
